# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------
TEMPLATE = subdirs

CONFIG += ordered

SUBDIRS = QExceptionDialog \
          QSqlModel \
          QPropPages \
          QIniSettings \
          QIndicatorWindow \
          IndicatorMain

