# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = subdirs

CONFIG += ordered

SUBDIRS = QExceptionDialog \
          QSqlModel \
          QPropPages \
          QIniSettings \
          QTargetsMap \
          QIndicatorWindow \
          IndicatorMain

win32 {
    !system(del /F RadarIndicator.exe)
}
