#ifndef QFINDICATOR_GLOBAL_H
#define QFINDICATOR_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef QLOCALCONTROLQMLWIDGET_LIBRARY
# define QLOCALCONTROLQMLWIDGET_EXPORT Q_DECL_EXPORT
#else
# define QLOCALCONTROLQMLWIDGET_EXPORT Q_DECL_IMPORT
#endif

#endif // QFINDICATOR_GLOBAL_H
