#ifndef QFINDICATORWIDGET_GLOBAL_H
#define QFINDICATORWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef QFINDICATORWIDGET_LIBRARY
# define QFINDICATORWIDGET_EXPORT Q_DECL_EXPORT
#else
# define QFINDICATORWIDGET_EXPORT Q_DECL_IMPORT
#endif

#endif // QFINDICATORWIDGET_GLOBAL_H
