#ifndef QEXCEPTIONDIALOG_GLOBAL_H
#define QEXCEPTIONDIALOG_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef QEXCEPTIONDIALOG_LIBRARY
# define QEXCEPTIONDIALOG_EXPORT Q_DECL_EXPORT
#else
# define QEXCEPTIONDIALOG_EXPORT Q_DECL_IMPORT
#endif

#endif // QEXCEPTIONDIALOG_GLOBAL_H
